version: '3.1'

services:

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
    - "27017:27017"
    volumes:
    - ./data/db:/data/db
    command: mongod --auth