version: '3.1'

services:

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: XKg`w3(p4ArBGQsD
    ports:
    - "27017:27017"
    volumes:
    - ./data/db:/data/db