version: "3.7"

services:
  node:
    image: node-dev
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/var/deploy/app
    command: npm run start
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      # - ./mongo-init-scripts:/docker-entrypoint-initdb.d:ro
      - ./data/db:/data/db
    command: mongod --auth
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped
      
